import { motion } from 'motion/react'
import { Button } from '../components/Button'
import { LinkedIn, Shield, XLogo } from '../components/Icons'
import { asset, assetSrcSet, brandLogos } from '../lib/assets'
import { ease, fadeUp, stagger } from '../lib/motion'

export function Hero() {
  return (
    <section id="top" className="relative overflow-hidden pt-16">
      <img
        src={asset('hero-clouds-cotton-blue-v7.png', 1920)}
        srcSet={assetSrcSet('hero-clouds-cotton-blue-v7.png')}
        sizes="100vw"
        alt=""
        aria-hidden
        fetchPriority="high"
        decoding="async"
        className="pointer-events-none absolute inset-0 -z-20 size-full object-cover object-bottom"
      />
      <div className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(62%_46%_at_50%_52%,rgb(255_255_255/0.6)_0%,rgb(255_255_255/0.24)_48%,transparent_74%)]" />
      <div className="pointer-events-none absolute inset-x-0 bottom-0 -z-10 h-64 bg-gradient-to-b from-transparent via-page/70 to-page" />

      <motion.div
        variants={stagger(0.09, 0.1)}
        initial="hidden"
        animate="show"
        className="mx-auto flex max-w-[1320px] flex-col items-center px-5 pt-14 pb-8 text-center sm:px-8 sm:pt-24"
      >
        <motion.div
          variants={fadeUp}
          className="flex items-center gap-2 rounded-full bg-white/90 px-3.5 py-1.5 shadow-[0_2px_14px_rgb(17_19_24/0.06)] backdrop-blur-sm"
        >
          <XLogo className="text-ink" />
          <span className="flex size-[18px] items-center justify-center rounded-[4px] bg-[#0A66C2] text-white">
            <LinkedIn width={11} height={11} />
          </span>
          <span className="text-[0.8125rem] font-medium text-ink sm:text-[0.9375rem]">
            Where B2B brands work with creators
          </span>
        </motion.div>

        <motion.h1
          variants={fadeUp}
          className="display mt-7 max-w-[41rem] text-[2.25rem] sm:text-[3.6rem] lg:text-[4.5rem]"
        >
          The B2B LinkedIn Creator Marketplace.
        </motion.h1>

        <motion.p
          variants={fadeUp}
          className="mt-5 max-w-[34rem] text-pretty text-[1.0625rem] leading-[1.5] text-ink-soft sm:text-[1.25rem]"
        >
          Find the creators your buyers already trust, launch campaigns in days, and track the
          clicks, leads and pipeline generated by every post.
        </motion.p>

        <motion.div
          variants={fadeUp}
          className="mt-8 flex w-full flex-col items-center gap-4 sm:w-auto sm:flex-row sm:gap-6"
        >
          <Button href="#cta" size="lg" arrow className="w-full sm:w-auto">
            Launch a campaign
          </Button>
          <Button href="#workflow" variant="link" size="lg" arrow>
            See how Naano works
          </Button>
        </motion.div>

        <motion.p
          variants={fadeUp}
          className="mt-7 flex items-center gap-2 text-[0.9375rem] text-[#55575e]"
        >
          <Shield className="text-faint" />
          Trusted by modern B2B teams
        </motion.p>
      </motion.div>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.6, duration: 0.8, ease }}
        className="marquee relative mx-auto max-w-[1320px] overflow-hidden pb-10 [mask-image:linear-gradient(to_right,transparent,black_8%,black_92%,transparent)]"
      >
        <div className="marquee-track flex w-max items-center">
          {[0, 1].map((copy) => (
            <ul key={copy} className="flex items-center" aria-hidden={copy === 1}>
              {brandLogos.map((logo) => (
                <li key={logo.name} className="flex w-[clamp(9rem,16vw,13rem)] justify-center px-4">
                  <img
                    src={asset(logo.file, 384)}
                    alt={copy === 0 ? logo.name : ''}
                    loading="lazy"
                    decoding="async"
                    className="h-8 w-auto max-w-full object-contain opacity-55 transition-opacity duration-300 hover:opacity-90 sm:h-9"
                  />
                </li>
              ))}
            </ul>
          ))}
        </div>
      </motion.div>
    </section>
  )
}
